name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0

    - name: Restore dependencies
      run: dotnet restore WebKlient.sln

    - name: Build solution
      run: dotnet build --configuration Release --no-restore WebKlient.sln

    - name: Run tests
      run: dotnet test --no-build --verbosity normal WebKlient.sln
